import type { Txn } from "./schema";
import { sliceBy, type Metrics } from "./metrics";
import type { Insight } from "./insights";
import type { Check } from "./insights";

/**
 * Take-away artefacts.
 *
 * An analysis nobody can get out of the tool is half a tool - the summary has to
 * land in a spreadsheet or an email. Both writers below quote every field, so a
 * customer name containing a comma survives the round trip; producing a CSV that
 * a CSV reader mis-parses would be a particularly poor look here.
 */
const q = (v: string | number): string => {
  const s = String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};

export function summaryCsv(txns: Txn[], m: Metrics): string {
  const lines: string[] = ["Section,Metric,Value"];
  const add = (section: string, metric: string, value: string | number) =>
    lines.push([q(section), q(metric), q(value)].join(","));

  add("Headline", "Revenue", m.headline.revenue.toFixed(2));
  if (m.headline.cost !== null) add("Headline", "Cost of goods", m.headline.cost.toFixed(2));
  if (m.headline.grossProfit !== null) add("Headline", "Gross profit", m.headline.grossProfit.toFixed(2));
  if (m.headline.marginPct !== null) add("Headline", "Gross margin %", m.headline.marginPct.toFixed(2));
  add("Headline", "Orders", m.headline.orders);
  add("Headline", "Units", m.headline.units);
  add("Headline", "Customers", m.headline.customers);
  add("Headline", "Average order value", m.headline.aov.toFixed(2));
  add("Headline", "Repeat rate %", (m.repeatRate * 100).toFixed(2));
  add("Headline", "Credit lines", m.headline.refunds);

  for (const p of m.months) {
    add("Monthly", `${p.month} revenue`, p.revenue.toFixed(2));
    if (p.marginPct !== null) add("Monthly", `${p.month} margin %`, p.marginPct.toFixed(2));
  }

  for (const dim of ["customer", "product", "category", "region", "channel", "rep"] as const) {
    for (const s of sliceBy(txns, dim, 10)) {
      add(`By ${dim}`, s.key, s.revenue.toFixed(2));
    }
  }
  return lines.join("\n");
}

/** A written report, ready to paste into an email or a doc. */
export function reportMarkdown(m: Metrics, insights: Insight[], checks: Check[]): string {
  const money = (n: number) =>
    n.toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
  const period = m.span
    ? `${m.span.from.toISOString().slice(0, 10)} to ${m.span.to.toISOString().slice(0, 10)}`
    : "unknown period";

  const out = [
    "# Sales performance summary",
    "",
    `**Period:** ${period}  `,
    `**Revenue:** ${money(m.headline.revenue)}  `,
    m.headline.grossProfit !== null ? `**Gross profit:** ${money(m.headline.grossProfit)}  ` : "",
    m.headline.marginPct !== null ? `**Gross margin:** ${m.headline.marginPct.toFixed(1)}%  ` : "",
    `**Orders:** ${m.headline.orders.toLocaleString()} · **Customers:** ${m.headline.customers.toLocaleString()} · **AOV:** ${money(m.headline.aov)}`,
    "",
    "## Findings",
    "",
  ].filter(Boolean);

  if (insights.length === 0) out.push("_No notable findings._", "");
  for (const i of insights) {
    out.push(`### ${i.title}`, "", i.detail, "", `**Recommended action:** ${i.action}`, "");
  }

  out.push("## Reconciliation", "");
  for (const c of checks) {
    out.push(`- ${c.ok ? "PASS" : "FAIL"} — ${c.label} (${money(c.actual)})`);
  }
  out.push("", "_Generated by REQUQU. Figures are derived from the supplied export only._");
  return out.join("\n");
}

/** Browser download without a server round-trip. */
export function download(filename: string, content: string, mime: string): void {
  const blob = new Blob([content], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  // Revoking immediately can cancel the download in some browsers; defer a tick.
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
